version: '3.8'

services:
  db:
    image: postgres:17
    container_name: study-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studydb  # será criado automaticamente
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Externa:5433 → Interna:5432

  web:
    build: .
    container_name: study-web
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: studydb
      DB_USER: postgres
      DB_PASS: postgres
    volumes:
      - .:/app  # <-- aqui está o bind mount
    ports:
      - "8001:8001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload  # <== Hot reload ativo

volumes:
  postgres_data:
